# Hugolify content available https://www.hugolify.io/docs/sections/

imports:
  # Specific Medicalify
  - path: github.com/uncinq/medicalify-theme

  # For exampleSite
  - path: github.com/hugolify/hugolify-theme-expertises
  - path: github.com/hugolify/hugolify-theme-services
  - path: github.com/hugolify/hugolify-theme-persons-expertises
  - path: github.com/hugolify/hugolify-theme-persons-statutes
  - path: github.com/hugolify/hugolify-theme-persons

  # Core theme
  - path: github.com/hugolify/hugolify-theme

  # CMS
  - path: github.com/hugolify/hugolify-admin
